compressionLevel: 0

enableGlobalCache: true

enableTelemetry: false

logFilters:
  - code: YN0002 # MISSING_PEER_DEPENDENCY
    level: discard
  - code: YN0005 # BUILD_DISABLED
    level: discard
  - code: YN0007 # MUST_BUILD
    level: discard
  - code: YN0008 # MUST_REBUILD
    level: discard
  - code: YN0013 # FETCH_NOT_CACHED
    level: discard
  - code: YN0060 # INCOMPATIBLE_PEER_DEPENDENCY
    level: discard

nmMode: hardlinks-local

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.2.cjs
